### ISSUE TITLE
Plugin finds and replaces without manipulating the DOM

### ISSUE THREAD

**Issue by Hilaryous** [leri/Easy-Replace#6]
I need to be able to tell whether or not any form fields within a form have been edited or manipulated, including when my users use your program. I've been trying for some time now to find a way to detect this. The problem is the plugin seems to leave virtually no traces.  I've tried taking the html markup when the page loads and then at a later time when I need to see if there are changes. But, no changes are made to the markup. I've also tried adding a MutableObserver, [like in this post](https://stackoverflow.com/questions/2844565/is-there-a-jquery-dom-change-listener/11546242#11546242), to track when a change is made to the DOM, but your plugin makes no changes to the DOM.

My question is do you guys have some kind of event that I can listen for? If not would it be possible to add one, to actually alter the markup or to manipulate the DOM in a significant enough way that it can be detected?

**Comment by leri** [comment]
Hello,

My program is a chrome extension. There's content script loaded in pages where user uses this extension. That content script has its own environment which is completely isolated from web-site's js scope, so conflicts won't happen. Basically, neither you have access to interact with content script, nor I have possibility to interact with your javascript.

I am manipulating only inputs and textareas, so I don't change any DOM objects. What you can do is to listen inputs on text change. However, I would never rely on client-side checks. May I see what your application is (so I can give you more detailed answer)?

**Comment by Hilaryous** [comment]
Thanks for getting back to be so quickly. Your plugin works very elegantly
and as it should. I was asked to do the impossible, but figured I'd give it
one last shot by asking you. I think I'll just pass on the message, no need
to do anything. Thanks Again.
